drop table product if exists;
create table product (
  id bigint generated by default as identity,
  name varchar(45),
  description varchar(45),
  price decimal(10,3),
  category varchar(45),
  primary key (id)
);
