spring:
  application:
    name: xy-inc
  profiles:
    active: dev
server:
  servlet:
    contextPath: /xy-inc
  port: 9000
app:
  project:
    path: projects
  api:
    log:
      size: 100
    start:
      automatically: true
